### ISSUE TITLE
Error: Cannot import name Serializer

### ISSUE THREAD

**Issue by ameygat** [haukurk/flask-restapi-recipe#4]
`python run.py -i` code dies with error Cannot import Serializer.
Is it issue with Marmallow version ?

```
(env) a@a-virtual-machine ~/api/flask-restapi-recipe $ pip install Serializer
Collecting Serializer
  Downloading Serializer-0.2.1.tar.gz
Requirement already satisfied: setuptools in /home/a/api/env/lib/python2.7/site-packages (from Serializer)
Collecting simplejson (from Serializer)
  Downloading simplejson-3.12.0-py2-none-any.whl (51kB)
    100% |████████████████████████████████| 61kB 270kB/s 
Building wheels for collected packages: Serializer
  Running setup.py bdist_wheel for Serializer ... done
  Stored in directory: /home/a/.cache/pip/wheels/a5/d1/e4/71d7902ec002fc5bad63f5f70a44a1c1b1b321b880fc27f407
Successfully built Serializer
Installing collected packages: simplejson, Serializer
Successfully installed Serializer-0.2.1 simplejson-3.12.0
(env) a@a-virtual-machine ~/api/flask-restapi-recipe $ python run.py -i
/home/a/api/flask-restapi-recipe/restapi/__init__.py:7: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
  from flask.ext.sqlalchemy import SQLAlchemy
/home/a/api/env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    from restapi import app, db
  File "/home/a/api/flask-restapi-recipe/restapi/__init__.py", line 40, in <module>
    from modules.cakes import mod as cakes_module
  File "/home/a/api/flask-restapi-recipe/restapi/modules/cakes/__init__.py", line 3, in <module>
    from controllers import mod
  File "/home/a/api/flask-restapi-recipe/restapi/modules/cakes/controllers.py", line 8, in <module>
    from restapi.modules.cakes.models import Cake, db, CakeSerializer
  File "/home/a/api/flask-restapi-recipe/restapi/modules/cakes/models.py", line 4, in <module>
    from marshmallow import Serializer, fields
ImportError: cannot import name Serializer

```

**Comment by sanfx** [comment]
after you source in the env , in python terminal import marshmallow and then check marshmallow.__file__ or just marshmallow, check if this is giving the path of the version you re expecting ! apart from that this is not related to the flask-restapi-recipie .
